spring:
  datasource:
    username: bshf
    password: 123456
    url: jdbc:mysql://localhost:3306/cfprs?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
server:
  port: 9000
